VERILOG = ../src/top_altair.v ../src/altair.v \
	  ../src/jmp_boot.v ../src/ram_memory.v ../src/rom_memory.v \
	  ../src/i8080.v ../src/mc6850.v ../src/simpleuart.v

PCF_FILE = blackice.pcf

include blackicemx.mk


